"""Hardcoded customer data for the CRMS demo."""

CUSTOMERS = [
    {
        "id": 1,
        "name": "Olivia Martinez",
        "company": "Brightline Logistics",
        "email": "olivia.martinez@brightline.com",
        "phone": "+1 (555) 210-4471",
        "status": "Active",
        "joinDate": "2022-03-14",
        "address": "482 Harbor Ave, Seattle, WA 98101",
        "totalOrders": 37,
        "totalSpent": 48250.75,
        "lastContact": "2026-06-28",
        "notes": "Key account. Prefers email communication. Renewal due in Q4.",
    },
    {
        "id": 2,
        "name": "Daniel Chen",
        "company": "Pixel & Pine Studio",
        "email": "daniel.chen@pixelpine.io",
        "phone": "+1 (555) 384-2209",
        "status": "Active",
        "joinDate": "2023-07-02",
        "address": "19 Birchwood Ln, Austin, TX 73301",
        "totalOrders": 12,
        "totalSpent": 9840.00,
        "lastContact": "2026-07-01",
        "notes": "Interested in upgrading to the enterprise tier.",
    },
    {
        "id": 3,
        "name": "Amara Okafor",
        "company": "Northwind Analytics",
        "email": "amara.okafor@northwindanalytics.com",
        "phone": "+1 (555) 917-6653",
        "status": "Inactive",
        "joinDate": "2021-11-19",
        "address": "77 Meridian St, Chicago, IL 60601",
        "totalOrders": 4,
        "totalSpent": 1620.50,
        "lastContact": "2025-12-10",
        "notes": "Account went dormant after main contact left the company.",
    },
    {
        "id": 4,
        "name": "Lucas Ferreira",
        "company": "Solaris Renewables",
        "email": "lucas.ferreira@solarisren.com",
        "phone": "+1 (555) 648-1102",
        "status": "Active",
        "joinDate": "2020-05-30",
        "address": "203 Sunview Dr, Denver, CO 80202",
        "totalOrders": 61,
        "totalSpent": 112430.20,
        "lastContact": "2026-07-09",
        "notes": "Long-standing customer. Eligible for loyalty discount.",
    },
    {
        "id": 5,
        "name": "Priya Sharma",
        "company": "Fernwood Health Group",
        "email": "priya.sharma@fernwoodhealth.org",
        "phone": "+1 (555) 772-9938",
        "status": "Pending",
        "joinDate": "2026-06-15",
        "address": "56 Willow Creek Rd, Portland, OR 97201",
        "totalOrders": 0,
        "totalSpent": 0.0,
        "lastContact": "2026-06-15",
        "notes": "New signup, onboarding call scheduled.",
    },
    {
        "id": 6,
        "name": "Marcus Webb",
        "company": "Ironclad Freight",
        "email": "marcus.webb@ironcladfreight.com",
        "phone": "+1 (555) 305-8814",
        "status": "Active",
        "joinDate": "2019-09-08",
        "address": "918 Dockside Blvd, Newark, NJ 07102",
        "totalOrders": 89,
        "totalSpent": 203890.00,
        "lastContact": "2026-07-11",
        "notes": "Largest account by volume. Assigned dedicated account manager.",
    },
]
